
#define VERSION_MAJOR 2
#define VERSION_MINOR 0

#define ADDR_VERSION_MAJOR 0x00
#define ADDR_VERSION_MINOR 0x04
/**
 * Esto parece super importante ya que dependiendo
 * de su valor se toma un camino u otro en ACI_Something
 */
#define ADDR_UNKNOWN 0x08
#define ADDR_NAME 0x0C
/**
 * Esto contiene algo que cuando se carga en un registro
 * se vuelve atrás, una posición.
 */
/*
#define ADDR_UNKNOWN 		0x10
#define ADDR_UNKNOWN 		0x14
#define ADDR_UNKNOWN 		0x18
#define ADDR_UNKNOWN 		0x1C
#define ADDR_UNKNOWN 		0x20
#define ADDR_UNKNOWN 		0x24
#define ADDR_UNKNOWN 		0x28
#define ADDR_UNKNOWN 		0x2C
#define ADDR_UNKNOWN 		0x30
#define ADDR_UNKNOWN 		0x34
#define ADDR_UNKNOWN 		0x38
#define ADDR_UNKNOWN 		0x3C
#define ADDR_UNKNOWN 		0x40
#define ADDR_UNKNOWN 		0x44
#define ADDR_UNKNOWN 		0x48
#define ADDR_UNKNOWN 		0x4C
#define ADDR_UNKNOWN 		0x50
#define ADDR_UNKNOWN 		0x54
#define ADDR_UNKNOWN 		0x58
#define ADDR_UNKNOWN 		0x5C
#define ADDR_UNKNOWN 		0x60
#define ADDR_UNKNOWN 		0x64
#define ADDR_UNKNOWN 		0x68
#define ADDR_UNKNOWN 		0x6C
#define ADDR_UNKNOWN 		0x70
#define ADDR_UNKNOWN 		0x74
#define ADDR_UNKNOWN 		0x78
#define ADDR_UNKNOWN 		0x7C
#define ADDR_UNKNOWN 		0x80
#define ADDR_UNKNOWN 		0x84
#define ADDR_UNKNOWN 		0x88
#define ADDR_UNKNOWN 		0x8C
#define ADDR_UNKNOWN 		0x90
#define ADDR_UNKNOWN 		0x94
#define ADDR_UNKNOWN 		0x98
#define ADDR_UNKNOWN 		0x9C
#define ADDR_UNKNOWN 		0xA0
#define ADDR_UNKNOWN 		0xA4
#define ADDR_UNKNOWN 		0xA8
#define ADDR_UNKNOWN 		0xAC
#define ADDR_UNKNOWN 		0xB0
#define ADDR_UNKNOWN 		0xB4
#define ADDR_UNKNOWN 		0xB8
#define ADDR_UNKNOWN 		0xBC
#define ADDR_UNKNOWN  		0xC0
#define ADDR_UNKNOWN  		0xC4
#define ADDR_UNKNOWN  		0xC8
#define ADDR_UNKNOWN  		0xCC
#define ADDR_UNKNOWN  		0xD0
#define ADDR_UNKNOWN  		0xD4
#define ADDR_UNKNOWN  		0xD8
#define ADDR_UNKNOWN  		0xDC
#define ADDR_UNKNOWN  		0xE0
#define ADDR_UNKNOWN  		0xE4
#define ADDR_UNKNOWN  		0xE8
#define ADDR_UNKNOWN  		0xEC
#define ADDR_UNKNOWN  		0xF0
#define ADDR_UNKNOWN 	 	0xF4
#define ADDR_UNKNOWN 		0xF8
#define ADDR_UNKNOWN 		0xFC
#define ADDR_UNKNOWN 		0x100
#define ADDR_UNKNOWN 		0x104
#define ADDR_UNKNOWN 		0x108
#define ADDR_UNKNOWN 		0x10C
#define ADDR_UNKNOWN 		0x110
#define ADDR_UNKNOWN 		0x114
#define ADDR_UNKNOWN 		0x118
#define ADDR_UNKNOWN 		0x11C
#define ADDR_UNKNOWN 		0x120
#define ADDR_UNKNOWN 		0x124
#define ADDR_UNKNOWN 		0x128
#define ADDR_UNKNOWN 		0x12C
#define ADDR_UNKNOWN 		0x130
#define ADDR_UNKNOWN 		0x134
#define ADDR_UNKNOWN 		0x138
#define ADDR_UNKNOWN 		0x13C
#define ADDR_UNKNOWN 		0x140
#define ADDR_UNKNOWN 		0x144
#define ADDR_UNKNOWN 		0x148
#define ADDR_UNKNOWN 		0x14C
#define ADDR_UNKNOWN 		0x150
#define ADDR_UNKNOWN 		0x154
#define ADDR_UNKNOWN 		0x158
#define ADDR_UNKNOWN 		0x15C
#define ADDR_UNKNOWN 		0x160
#define ADDR_UNKNOWN 		0x164
#define ADDR_UNKNOWN 		0x168
#define ADDR_UNKNOWN 		0x16C
*/
